apiVersion: v1
kind: Pod
metadata:
  name: sample-demo
  namespace: sample
spec:
  containers:
    - name: my-app3
      image: my/app3
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: "1"
        requests:
          cpu: "0.5"
      args:
        - -cpus
        - "2"